name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
      TF_VAR_openweather_api_key: ${{ secrets.OPENWEATHER_API_KEY }}
      TF_VAR_tomtom_api_key: ${{ secrets.MYTOMTOM_API_KEY }}
      TF_VAR_openaq_api_key: ${{ secrets.OPENAQ_API_KEY }}

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve